import type { Metadata } from "next"
// import localFont from "next/font/local";
import "./globals.css"
import { ReactNode } from "react"
import { Amatic_SC } from "next/font/google"
import { Providers } from "./providers"

const amatic = Amatic_SC({
  weight: ["400", "700"], // Доступные веса шрифта
  subsets: ["latin", "cyrillic"], // Наборы символов
  display: "swap", // Оптимизация рендеринга шрифта
})
// import Head from "next/head"
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Imaginarium",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon4.ico",
  },
  // icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundImage: "url('/cloud.jpg')",
        }}
        className={amatic.className}
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
